### ISSUE TITLE
Sakai 19 and 20 persistence

### ISSUE THREAD

**Issue by mpellicer** [sakaicontrib/attendance#37]
After the JPA changes of Rubrics, many tools required some changes in the persistence layer. 
This tool is affected by the JPA changes too, this is what happens when you try to remove an event in Sakai 19 or Sakai 20:

`Caused by: java.lang.IllegalArgumentException: Removing a detached instance org.sakaiproject.attendance.model.AttendanceEvent#3
	at org.hibernate.jpa.event.internal.core.JpaDeleteEventListener.performDetachedEntityDeletionCheck(JpaDeleteEventListener.java:69)
	at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:106)
	at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:73)
	at org.hibernate.internal.SessionImpl.fireDelete(SessionImpl.java:956)
	at org.hibernate.internal.SessionImpl.delete(SessionImpl.java:896)
	at org.springframework.orm.hibernate4.HibernateTemplate$24.doInHibernate(HibernateTemplate.java:794)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:341)
	at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:309)
	at org.springframework.orm.hibernate4.HibernateTemplate.delete(HibernateTemplate.java:787)
	at org.springframework.orm.hibernate4.HibernateTemplate.delete(HibernateTemplate.java:782)
	at org.sakaiproject.attendance.dao.impl.AttendanceDaoImpl.deleteAttendanceEvent(AttendanceDaoImpl.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy99.deleteAttendanceEvent(Unknown Source)
	at org.sakaiproject.attendance.logic.AttendanceLogicImpl.deleteAttendanceEvent(AttendanceLogicImpl.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:484)
	at com.sun.proxy.$Proxy347.deleteAttendanceEvent(Unknown Source)
	at org.sakaiproject.attendance.tool.panels.EventInputPanel$1.onClick(EventInputPanel.java:93)
	at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:86)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:145)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:649)
	... 60 more`

![image](https://user-images.githubusercontent.com/8653754/48413511-3ce37000-e748-11e8-96b2-101a948b40ad.png)

**Comment by mpellicer** [comment]
Resolved here:

https://github.com/sakaicontrib/attendance/pull/39

**Comment by ottenhoff** [comment]
Thanks for the PR
