### ISSUE TITLE
Export NPE

### ISSUE THREAD

**Issue by ottenhoff** [sakaicontrib/attendance#80]
Caused by: java.lang.NullPointerException
        at org.sakaiproject.attendance.tool.pages.ExportPage.buildExcelFile(ExportPage.java:210)
        at org.sakaiproject.attendance.tool.pages.ExportPage.access$000(ExportPage.java:58)
        at org.sakaiproject.attendance.tool.pages.ExportPage$3.load(ExportPage.java:105)
        at org.sakaiproject.attendance.tool.pages.ExportPage$3.load(ExportPage.java:101)
        at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:124)
        at org.apache.wicket.Component.getDefaultModelObject(Component.java:1612)
        ... 64 more

**Comment by jonespm** [comment]
This was fixed in #81
